/**
 * This component fetches and displays a list of products from a Medusa API.
 * It takes `endpoint` and `apiKey` as props to make authenticated requests to the Medusa API.
 * The fetched products are stored in the component's state and rendered as a list.
 *
 * Keep in mind that this is mostly generated by copilot for quick prototyping.
 */

'use client';

import React, { useEffect, useState } from 'react';
import axios from 'axios';

interface MedusaProductsProps {
  endpoint: string;
  apiKey: string;
}

const MedusaProducts: React.FC<MedusaProductsProps> = ({ endpoint, apiKey }) => {
  const [products, setProducts] = useState<any[]>([]);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const response = await axios.get(`${endpoint}/store/products`, {
          headers: { Authorization: `Bearer ${apiKey}` },
        });
        setProducts(response.data.products);
      } catch (error) {
        console.error('Error fetching products:', error);
      }
    };

    fetchProducts();
  }, [endpoint, apiKey]);

  return (
    <div>
      <h2>Medusa Products</h2>
      <ul>
        {products.map((product) => (
          <li key={product.id}>{product.title}</li>
        ))}
      </ul>
    </div>
  );
};

export default MedusaProducts;
